### ISSUE TITLE
 Segmentation fault

### ISSUE THREAD

**Issue by TinyFr0g** [cuamckuu/nfc-frog#11]
error libnfc.driver.pn532_spi Application level error detected

<a href="https://ibb.co/tC0Fxyj"><img src="https://i.ibb.co/q1HVWbq/Untitled.jpg" alt="Untitled" border="0"></a>

i got the same issues on i2c spi and usb interface....

**Comment by TinyFr0g** [comment]
@cuamckuu i got the same problem now with UART on both readers 
<a href="https://ibb.co/4WV41vm"><img src="https://i.ibb.co/Wn2BV8x/Untitled3.jpg" alt="Untitled3" border="0"></a>

i run the command with sudo on both SPI and I2C on the last 2 test
what version of libnfc do you have installed?

**Comment by cuamckuu** [comment]
Last time I used latest from [releases page](https://github.com/nfc-tools/libnfc/releases), but now I don't have any hardware wired to test.

What was the output from `sudo nfc-scan-device` and `sudo nfc-list`

**Comment by TinyFr0g** [comment]
> 
> 
> Last time I used latest from [releases page](https://github.com/nfc-tools/libnfc/releases), but now I don't have any hardware wired to test.
> 
> What was the output from `sudo nfc-scan-device` and `sudo nfc-list`?

pi@raspberrypi:~/Downloads/nfc-frog $ sudo nfc-scan-device
nfc-scan-device uses libnfc libnfc-1.8.0-61-g6d0e8a5
1 NFC device(s) found:
- PN532 board via UART:
    pn532_uart:/dev/ttyS0


pi@raspberrypi:~/Downloads/nfc-frog $ sudo nfc-list
NFC device: PN532 board via UART opened
error	libnfc.driver.pn532_uart	Application level error detected
error	libnfc.driver.pn532_uart	Application level error detected

**Comment by cuamckuu** [comment]
So it's a problem with the way you connected your reader to board. Google some tutorials and pins schemes for proper connection
