### ISSUE TITLE
Отказывается работать с visa (или сбером)

### ISSUE THREAD

**Issue by DjamikTea** [cuamckuu/nfc-frog#14]
Привет, я использую твой код чтоб считывать PAN для скуда и у меня проблема что с картой visa сбера он отказывается работать (скорее всего из-за того что PDOL не устраивает), но с Мастеркардом все норм

Вот что выдает
![Снимок экрана 2021-12-29 в 15 47 52](https://user-images.githubusercontent.com/34600049/147664512-0dcffaba-d504-4a2d-84c8-e4859031dcf4.png)
(на всякий случай скрыл)
![IMG_5128](https://user-images.githubusercontent.com/34600049/147664570-fcdf5baf-3d72-4b94-82e5-10bab08d5d71.PNG)

**Comment by cuamckuu** [comment]
Привет, я тестировал только на физических картах, пытался с парой виртуальных карт на телефоне, но там немного другой формат, с которым не разбирался

**Comment by DjamikTea** [comment]
C пластиковой тоже самое

**Comment by cuamckuu** [comment]
А на скрине что не так? Прошли же там "read records", значит данные считались, теперь их нужно засунуть в парсер

**Comment by DjamikTea** [comment]
там нету PANа
![Снимок экрана 2021-12-29 в 22 18 22](https://user-images.githubusercontent.com/34600049/147696530-8dc7ab3f-efed-4090-a03c-cd79ad5cda22.png)

вот мастеркард:
![Снимок экрана 2021-12-29 в 22 21 57](https://user-images.githubusercontent.com/34600049/147696562-4da2fb03-883d-4d49-93ea-967f69ce2cfe.png)

**Comment by cuamckuu** [comment]
Могу посоветовать другие режимы работы, может с ними получится:

```
sudo ./nfc-frog fast # Fast brute mode
sudo ./nfc-frog full # Full brute mode
```

А так, по скринам не особо понятно, что происходит и не получится воспроизвести для исправления

**Comment by cuamckuu** [comment]
Вообще, если всё что нужно - это уникально идентифицировать NFC карту, то использовать PAN плохая идея.

Там есть встреенные id, которые можно вытащить сильно проще, например через `nfc-pool` или `nfc-list`

**Comment by DjamikTea** [comment]
с fast он также пишет Could not complete payment и Segmentation fault, а вот с full он просит попробовать другую карту. с пластиком тоже ничего не дает

**Comment by cuamckuu** [comment]
Ну платёж он и не должен завершать, потому что это не программа для платежей. По поводу скрина выше, там тег "5F34", в интернете пишут, что это тег от Google/Apple pay, так что подозреваю, что с пластиком вывод другой

И ещё, для парсинга надо копировать не один вывод "Read record", а всё, что выведется при запуске 

```
sudo ./nfc-frog fast 2>/dev/null
```

**Comment by DjamikTea** [comment]
> ```
> sudo ./nfc-frog fast 2>/dev/null
> ```

could not complete payment и данные те же самые

я кстати добавил в массив PDOLValues это
` {0x9F66, new byte_t[4]{0xC8, 0x80, 0x00, 0x00}},`
и у меня подтвердился платёж, но данные опять те же
![Снимок экрана 2021-12-29 в 22 42 16](https://user-images.githubusercontent.com/34600049/147697997-3dba815c-6a4e-4a80-bfa4-e49f19cf1781.png)

**Comment by cuamckuu** [comment]
Подумал тут ещё, можно запустить команду 

```bash
sudo ./nfc-frog full 2>/dev/null
```

И там по выводу поискать руками PAN, чтобы понять есть ли он вообще, и какому тегу соответствует.

Ещё в начале общения карты и ридера происходит запрос приложений и выбор первого из них. Может быть на этой карте два приложения и нужно брать не первое...

**Comment by DjamikTea** [comment]
Неа, просит другую карту

**Comment by DjamikTea** [comment]
Ок, я дибил и просто не увидел что PAN хранится в Track 2 Equivalent Data (0x57) ,там же и дата. Это не очень понятный трюк от Visa для меня, например MASTERCARD дублирует это отдельно и даже MIR 
![Снимок экрана 2022-03-24 в 23 16 38](https://user-images.githubusercontent.com/34600049/160002918-397f1a80-9caa-4cbb-8e5c-d9e5fa92ca28.png)
![Снимок экрана 2022-03-24 в 23 13 51](https://user-images.githubusercontent.com/34600049/160002951-4ac12dd8-d75a-471b-b475-c5e263bd8687.png)
