### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by lps83** [cuamckuu/nfc-frog#2]
Hi, I just tried your lib in different mode; I just have a lot of Hexa in my console and then a Segmentation fault. Do you have any idea ? 
Im trying on raspbian.

Thanks

Edit : 
device_nfc.cpp:89
std::count << HEX(ret.data[I]) << " ";

**Comment by cuamckuu** [comment]
Hi, I think, that it's kind of "hardware" error, not software. 

**Make sure that you hold your card near nfc-scanner long enought (and close enought)**. If you will move card away, then there will be a segfault, I used to see same thing several times before.

**Comment by lps83** [comment]
Thanks for your answer. 
I'm going to try with an official Adafruid PN532. Do you think the raspberry pi can be the problem ?

**Comment by lps83** [comment]
Just tried with another PN532 board and a new FTDI cable on my other linux ...

`
sudo ./nDc-Drog Dull
[InDo] NDC reFder: pn432_uFrt:/dev/ttyUSB0 opened.

error	libnfc.driver.pn532_uart	application level error detected
[InDo] Response Drom SELECT PPSE: 00 00 ...  45Erreur de segmentation

`

**Comment by cuamckuu** [comment]
As I said: **Make sure that you hold your card near nfc-scanner long enought (and close enought)**

Also you can check that required `libnfc` works correctly by running `nfc-list` and `nfc-pool` with your card or with another one.
