### ISSUE TITLE
Does exist method to call beep inside device when card is attached?

### ISSUE THREAD

**Issue by Rombersoft** [cuamckuu/nfc-frog#3]

**Comment by cuamckuu** [comment]
This is part from `main.cpp`, that might be helpful. It will wait for card to be attached and then calls for `beep()` function which you can define yourself

```
        DeviceNFC device;
        std::cerr << "[Info] NFC reader: " << device.get_name() << " opened.\n";

        while (!device.pool_target()) {
            std::cerr << "[Info] Searching card..." << std::endl;
            std::this_thread::sleep_for(std::chrono::seconds(1));
        }
        beep() // Here is your code
```

**Comment by Rombersoft** [comment]
Is it beep on motherboard or in nfc-reader?

**Comment by cuamckuu** [comment]
You should define that function yourself and make "beep" and other stuff you want there, that's why there is comment

**Comment by Rombersoft** [comment]
Thank you very much. Very useful advise!
