### ISSUE TITLE
What hw does this works on?

### ISSUE THREAD

**Issue by costiganb** [cuamckuu/nfc-frog#9]
Great project!

Can this be installed on a smartphone with termux?

**Comment by cuamckuu** [comment]
Hi, nfc-frog uses [libnfc](https://github.com/nfc-tools/libnfc#installation) which grants support for pn532 readers like this:

![image](https://user-images.githubusercontent.com/15267331/125069917-11afab00-e0c0-11eb-8974-e695ead4d27d.png)

I used that reader with Raspberry Pi ang Oragre Pi. Not sure if it could be used with Android phone directly.

For Android it might be better to use something like [this](https://github.com/nadam/nfc-reader) or [this](https://github.com/Peerbits/Android-NFC)

**Comment by costiganb** [comment]
Great, thank you @cuamckuu  for answering!
